export enum RoleName {
  SUPER_ADMIN = 'SUPER_ADMIN',
  AUCTION_ADMIN = 'AUCTION_ADMIN',
  AUCTION_MANAGER = 'AUCTION_MANAGER',
  FINANCE = 'FINANCE',
  AUDITOR = 'AUDITOR',
  EMPLOYEE = 'EMPLOYEE',
}
